"""empty message

Revision ID: f16474637df4
Revises: d8c229fba653
Create Date: 2022-03-29 15:19:52.511649

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f16474637df4'
down_revision = 'd8c229fba653'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('planet_id', sa.Integer(), nullable=False))
    op.drop_constraint('people_ibfk_1', 'people', type_='foreignkey')
    op.create_foreign_key(None, 'people', 'planet', ['planet_id'], ['id'])
    op.drop_column('people', 'homeplanet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('homeplanet', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'people', type_='foreignkey')
    op.create_foreign_key('people_ibfk_1', 'people', 'planet', ['homeplanet'], ['id'])
    op.drop_column('people', 'planet_id')
    # ### end Alembic commands ###
